version: "3.7"
services:
  front:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
    container_name: frontend
    env_file: 
       - .env
    environment:
       - DJANGO_SETTINGS_MODULE=backend.settings
       - APP_FRONT_PORT= 3000
       - APP_FRONT_HOST= http://localhost:3000/
    ports:
      - "3000:3000"
    volumes:
      - front_data:/frontend
    
  back:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend
    env_file: 
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - APP_BACK_PORT= 8000
      - ALLOWED_HOST= 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - front
      - db
    volumes:
      - back_data:/backend
    command: python3 manage.py runserver 0.0.0.0:8000
  
  db:
    image: postgres
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
       
volumes:
  front_data:
  back_data:

  
